version: '3.5'

services:

  etcd0:
    image: quay.io/coreos/etcd
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd0:2379

  mon0:
    image: flaviostutz/ceph-monitor
    environment:
      - ETCD_URL=http://etcd0:2379
      - PEER_MONITOR_HOST=mon1
      - CREATE_CLUSTER_IF_PEER_DOWN=true

  mon1:
    image: flaviostutz/ceph-monitor
    environment:
      - ETCD_URL=http://etcd0:2379
      - PEER_MONITOR_HOST=mon0

  mgr1:
    build: .
    ports:
      - 18443:8443 #dashboard https
      - 18003:8003 #restful https
      - 19283:9283 #prometheus
    environment:
      - LOG_LEVEL=0
      - PEER_MONITOR_HOST=mon0
      - ETCD_URL=http://etcd0:2379

  mgr2:
    build: .
    ports:
      - 28443:8443 #dashboard https
      - 28003:8003 #restful https
      - 29283:9283 #prometheus
    environment:
      - LOG_LEVEL=0
      - PEER_MONITOR_HOST=mon0
      - ETCD_URL=http://etcd0:2379

  osd1:
    image: flaviostutz/ceph-osd
    environment:
      - PEER_MONITOR_HOST=mon0
      - OSD_EXT4_SUPPORT=true
      - OSD_JOURNAL_SIZE=512
      - ETCD_URL=http://etcd0:2379

  osd2:
    image: flaviostutz/ceph-osd
    environment:
      - PEER_MONITOR_HOST=mon0
      - OSD_EXT4_SUPPORT=true
      - OSD_JOURNAL_SIZE=512
      - ETCD_URL=http://etcd0:2379

  osd3:
    image: flaviostutz/ceph-osd
    environment:
      - PEER_MONITOR_HOST=mon0
      - OSD_EXT4_SUPPORT=true
      - OSD_JOURNAL_SIZE=512
      - ETCD_URL=http://etcd0:2379
